# Generated by Django 5.0.6 on 2024-11-14 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_notification_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
